_wandb:
    value:
        cli_version: 0.26.1
        e:
            1c69ndqwky7vho5xb1jhrb0i8byuxsmy:
                codePath: a_frozen_lake_q_learning.py
                codePathLocal: a_frozen_lake_q_learning.py
                cpu_count: 10
                cpu_count_logical: 20
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "392056897536"
                        used: "380298489856"
                email: wicked3365@gmail.com
                executable: C:\Users\Smart CPS\anaconda3\python.exe
                gpu: NVIDIA GeForce RTX 3090
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10496
                      memoryTotal: "25769803776"
                      name: NVIDIA GeForce RTX 3090
                      uuid: GPU-395ec490-b0f6-6f7a-03e3-d81bc86e4e03
                host: DESKTOP-5UQUJK4
                memory:
                    total: "34175610880"
                os: Windows-10-10.0.19045-SP0
                program: C:\Users\Smart CPS\Desktop\인공지능특강\HW1\link_rl-main\_01_code\_08_SARSA_Q_Learning\a_frozen_lake_q_learning.py
                python: CPython 3.10.13
                root: C:\Users\Smart CPS\Desktop\인공지능특강\HW1\link_rl-main\_01_code\_08_SARSA_Q_Learning
                startedAt: "2026-05-04T01:22:43.085966Z"
                writerId: 1c69ndqwky7vho5xb1jhrb0i8byuxsmy
        m: []
        python_version: 3.10.13
        t:
            "3":
                - 2
                - 16
                - 41
            "4": 3.10.13
            "5": 0.26.1
            "8":
                - 3
            "12": 0.26.1
            "13": windows-amd64
alpha:
    value: 0.1
epsilon:
    value: 0.1
gamma:
    value: 0.95
num_episodes:
    value: 50000
validation_num_episodes:
    value: 10
validation_time_steps_interval:
    value: 1000
